title: AltTabAlternative
author: Lokesh Govindu
email: lokeshgovindu@gmail.com
description: An alternative for windows native task switcher.
theme: jekyll-theme-hacker
show_excerpts: true # set to false to remove excerpts on the homepage
